short_texts = [
    "The quick brown fox jumps over the lazy dog.",
    "A journey of a thousand miles begins with a single step.",
    "Life is what happens when you're busy making other plans.",
    "To be or not to be, that is the question.",
    "All that glitters is not gold.",
    "Actions speak louder than words.",
    "Time flies when you're having fun.",
    "Where there's a will, there's a way.",
    "Beauty is in the eye of the beholder.",
    "The early bird catches the worm.",
    "Every cloud has a silver lining.",
    "Don't count your chickens before they hatch.",
    "Rome wasn't built in a day.",
    "You can't have your cake and eat it too.",
    "Haste makes waste.",
    "When in Rome, do as the Romans do.",
    "Necessity is the mother of invention.",
    "Two wrongs don't make a right.",
    "The pen is mightier than the sword.",
    "Love is blind.",
    "Where there is smoke, there is fire.",
    "Practice makes perfect.",
    "When the going gets tough, the tough get going.",
    "If the shoe fits, wear it.",
    "Every dog has its day.",
    "All is fair in love and war.",
    "Don't put all your eggs in one basket.",
    "The proof is in the pudding.",
    "A watched pot never boils.",
    "A rolling stone gathers no moss.",
    "Actions speak louder than words.",
    "Beggars can't be choosers.",
    "Better late than never.",
    "Curiosity killed the cat.",
    "Don't bite the hand that feeds you.",
    "Don't count your chickens before they hatch.",
    "Don't judge a book by its cover.",
    "Don't put all your eggs in one basket.",
    "Don't put off until tomorrow what you can do today.",
    "Don't throw the baby out with the bathwater.",
    "Every cloud has a silver lining.",
    "Every dog has its day.",
    "Good things come to those who wait.",
    "If the shoe fits, wear it.",
    "If you can't beat them, join them.",
    "It's a piece of cake.",
    "It's not rocket science.",
    "Let bygones be bygones.",
    "Let sleeping dogs lie.",
    "Like father, like son.",
    "Money doesn't grow on trees.",
    "Never say never.",
    "No pain, no gain.",
    "Once bitten, twice shy.",
    "Out of sight, out of mind.",
    "Practice makes perfect.",
    "Rome wasn't built in a day.",
    "The early bird catches the worm.",
    "The grass is always greener on the other side.",
    "The proof is in the pudding.",
    "There's no place like home.",
    "Third time's a charm.",
    "Time is money.",
    "Too many cooks spoil the broth.",
    "Two heads are better than one.",
    "When in Rome, do as the Romans do.",
    "You can't have your cake and eat it too.",
    "You can't judge a book by its cover.",
    "You can't make an omelet without breaking eggs.",
    "You reap what you sow.",
    "A picture is worth a thousand words.",
    "An apple a day keeps the doctor away.",
    "Don't cry over spilled milk.",
    "Every man for himself.",
    "Fortune favors the bold.",
    "Haste makes waste.",
    "Home is where the heart is.",
    "If it ain't broke, don't fix it.",
    "In the nick of time.",
    "It's a small world.",
    "It's a win-win situation.",
    "Keep your friends close and your enemies closer.",
    "Laughter is the best medicine.",
    "Look before you leap.",
    "Make hay while the sun shines.",
    "One man's trash is another man's treasure.",
    "Out of the frying pan, into the fire.",
    "People who live in glass houses shouldn't throw stones.",
    "The best things in life are free.",
    "The early bird gets the worm.",
    "The more, the merrier.",
    "There's no smoke without fire.",
    "To each his own.",
    "What goes around comes around.",
    "When the cat's away, the mice will play.",
    "You can't teach an old dog new tricks.",
    "You're a snake in the grass.",
    "A stitch in time saves nine.",
    "Absence makes the heart grow fonder.",
    "All good things must come to an end."
]
